theme: minima
sass:
  style: compressed

minima:
  nav_pages:
    - index.md
  
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
